uClibc-0.9.28:  * backport move_dl_iterate_phdr-patch  * fixes "libgcc_s.so: undefined reference to `dl_iterate_phdr'"-problem and all other problems it causes (like broken c++-compiler, broken libtool-host package, all packages with replaced libtool don't compile and so on)  * refs #842  * only rudimentary tested on Fritz!Box Fon WLAN (08.04.34), more feedback, especially if some packages stop working after this patch, is welcome
git-svn-id: http://svn.freetz.org/trunk@6165 f5190166-0702-4917-9039-51ec32eddaf5