fakeroot: add BIARCH_LD_PRELOAD_PATH to the list of search paths unconditionally.
Fixes the following build problem
 ERROR: ld.so: object 'libfakeroot.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

The problem appears on 64-bit systems after switching from a 64-bit self-built to a 32-bit download toolchain.

(cherry picked from commit dcfa0aa9d59f6fb0407985882f6a46a83d71eb5a)