ImageMagick: disable locale support for all uClibc versions unconditionally
Workarounds

 In file included from ./MagickCore/studio.h:109:0,
                  from MagickCore/locale.c:42:
 MagickCore/locale.c: In function 'LocaleLowercase':
 MagickCore/locale.c:1528:12: error: dereferencing pointer to incomplete type 'struct __uclibc_locale_struct'
      return(tolower_l((int) ((unsigned char) c),c_locale));
             ^
 MagickCore/locale.c: In function 'LocaleUppercase':
 MagickCore/locale.c:1668:12: error: dereferencing pointer to incomplete type 'struct __uclibc_locale_struct'
      return(toupper_l((int) ((unsigned char) c),c_locale));
             ^

observed with uClibc-1.0.14. Not sure if it's a uClibc or an ImageMagick issue. Disabling locale support is
however harmless - tolower_l/toupper_l are the only calls it's needed for. Both calls were added in Jan 2019
https://github.com/ImageMagick/ImageMagick/commit/d8bcdf1138d422274359da8d775514dee936495a#diff-cb574b95d0035916ba5d35355ddc05da